version: 0.2

env:
  parameter-store:
    rate-map: "rate-map"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
    - npm install
  build:
    commands:
#      - npm run test
      - npm run check
      - rm -rf node_modules
      - npm install --only=prod
      - aws cloudformation package --debug --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yaml
artifacts:
  type: zip
  files:
    - template-export.yaml

