version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 10 
    commands:
    - npm install --only=prod
    - npm run test
  build:
    commands:
      - aws cloudformation package --debug --template template.yaml --s3-bucket $S3_BUCKET --output-template template-export.yaml
      - ls -ltr
artifacts:
  type: zip
  files:
    - template-export.yaml
